# Generated by Django 2.2 on 2023-04-21 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Предмет обучения',
                'verbose_name_plural': 'Предметы обучения',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата проведения')),
                ('status', models.BooleanField(choices=[(True, 'Завершено'), (False, 'Не завершено')], default=False, verbose_name='Состояние занятия')),
                ('missing_students', models.ManyToManyField(blank=True, null=True, to='people.Student', verbose_name='Отсутствующие студенты')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.StudentGroup', verbose_name='Группы обучаемых')),
                ('study_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='lessons.StudySubject', verbose_name='Предмет обучения')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.Teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
    ]
