# Generated by Django 2.2 on 2023-04-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20230422_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='missing_students',
            field=models.ManyToManyField(blank=True, to='people.Student', verbose_name='Отсутствующие студенты'),
        ),
    ]
